apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datapower-operator
  namespace: apic
spec:
  channel: v1.17
  name: datapower-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace