apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:

- ../../../../components/apic/variants/nonprod
- ../../../../components/apic/variants/cloudprovider/iks

resources:
- ../../../../components/apic/base