apiVersion: management.apiconnect.ibm.com/v1beta1
kind: ManagementCluster
metadata:
  name: management
spec:
  license:
    accept: true
    use: nonproduction
    #license: 'L-AMGN-4YQ9TJ'
    license: L-CXFF-XRSP3J