apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#components:

#- ../../../../components/datapower/variants/cloudprovider/odf
#- ../../../../components/datapower/variants/nonprod

resources:
- ../../../../components/datapower/base