apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  backendTLS:
    minVersion: "1.3"
    maxVersion: "1.3"
  # Required: Enable gateway merging for API Connect
  mergeGateways: true
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 3
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/component: proxy
                      app.kubernetes.io/managed-by: envoy-gateway
                  topologyKey: kubernetes.io/hostname
  telemetry:
    accessLog:
      settings:
        - format:
            type: Text
            text: |
              [%START_TIME%] "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)% %PROTOCOL%" %RESPONSE_CODE% route=%ROUTE_NAME% vhost=%VIRTUAL_HOST_NAME% upstream=%UPSTREAM_HOST%
          sinks:
            - type: File
              file:
                path: /dev/stdout